project:
  type: website

website:
  title: "Johanna Mayer"
  page-footer:
    left: "© Johanna Mayer"
  navbar:
    center:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: false

filters:
  - include-files.lua
  - quarto
