---
title: "Peer-reviewed Publications"
---

last update (Sep. 2026). Updated listing under [Google Scholar](https://scholar.google.com/citations?user=zWTSjSIAAAAJ&hl=de&oi=sra) or [Orcid](https://orcid.org/0000-0002-9691-9534).

- B. Piskala Gvoždíková, J. Mayer, S.M. Brose, E. Malina, D. Gasbarra, A. Doležalová, K. Samardzhiev (2026).  
  Lightning2EarthCARE: Collocated geostationary lightning and EarthCARE observations of electrically active storms.  
  Earth System Science Data [preprint]. [https://doi.org/10.5194/essd-2026-470](https://doi.org/10.5194/essd-2026-470)

- J. Mayer, D. Gasbarra, R.J. Hogan, E. Malina, S. Mason, B. Piskala Gvozdikova (2026).  
  EarthCARE reveals details on the role of rain in closed-to-open cell transitions,  
  EGUsphere [preprint], doi:10.5194/egusphere-2026-3000

- J. Schaefer, S. Grawe, H.-C. Clemen, S. Mertes, J. Schneider, B. Wetzel, D. Sauer, J. Wolf, L. Tomsche, J. Mayer, R. Schrödner, S. Henning, T. Jurkat-Witschas, C. Voigt, H. Ziereis, T. Harlaß, M. Pöhlker, F. Stratmann (2026).  
  Upward transport and segregation of ice-nucleating particles in deep convective clouds.  
  Atmospheric Chemistry and Physics. doi:10.5194/acp-26-12505-2026

- H.K. Alladi, J. Quimbayo-Duarte, L. Bugliaro, J. Mayer, S. Singh, J. Schmidli (2026).  
  Evaluating turbulent and microphysical schemes in ICON for deep convection over the Alps: a case study of vertical transport and model–observation comparison,  
  Atmospheric Chemistry and Physics. doi:10.5194/acp-26-8617-2026

- M. Moser, C. Voigt, O. Eppers, J. Lucke, E. De La Torre Castro, J. Mayer, R. Dupuy, G. Mioche, O. Jourdan, H.-C. Clemen, J. Schneider, P. Joppe, S. Mertes, B. Wetzel, S. Borrmann, M. Klingebiel, M. Mech, C. Lüpkes, S. Crewell, A. Ehrlich, A. Herber, M. Wendisch (2026).  
  The Arctic Low-Level Mixed-Phase Haze Regime and its Microphysical Differences to Mixed-Phase Clouds.  
  Atmospheric Chemistry and Physics. doi:10.5194/acp-26-1867-2026

- V. Santos Gabriel, L. Bugliaro, M. Montag, S. Ries, Z. Wang, K. Widmaier, M. Arico, S. Unterstrasser, J. Mayer, D. Menekay, A. Marsing, E. de la Torre Castro, L. Megill, M. Scheibe, C. Voigt (2026).  
  A manually labeled contrail dataset from MSG/SEVIRI,  
  Earth System Science Data, doi:10.5194/essd-18-2397-2026

- B. Stevens, T. Andrews, F.A.-M. Bender, S. Bony, P. Ceppi, F. Glassmeier, H.M. Glöckner, J. Gregory, N.G. Loeb, H. Masunaga, B. Meyssignac, G. Myhre, M. Rugenstein, C.E. Singer, B. Soden, A. Aubel, G. Bellon, M. Bolot, N. Clerbaux, R. Fiévet, E. Fons, M.A. Giorgetta, O. Hadas, C. Hohenegger, L. Kluft, K. Krueger, J. Lécuyer, T. Mauritsen, B. Mayer, J. Mayer, M. Mayer, B. McKim, T. Michibata, R. Orlijan-Rhyne, C. Park, W. Roh, B.H. Samset, M. Satoh, G.A. Schmidt, M. Schulz, C. Smith, G. Tselioudis, Y. Tsushima, L. Volkmer, L.J. Wilcox (2026)  
  Earth’s net incoming energy-flux imbalance (and its implications for understanding climate change)  
  MPI für Meteorologie, doi:10.17617/2.3711842

- M. Aricò, D. Piontek, L. Bugliaro, J. Mayer, R. Müller, F. Kalinka, M. Butter (2025).  
  A novel machine learning retrieval for the detection of ice crystal icing conditions based on geostationary satellite imagery.  
  Atmospheric Measurement Techniques. doi:10.5194/amt-18-7129-2025

- T. Jurkat-Witschas, C. Voigt, S. Groß, S. Kaufmann, D. Sauer, E. De la Torre Castro, M. Krämer, A. Schäfler, A. Afchine, R. Attinger, I. Bartolome Garcia, C.G. Beer, L. Bugliaro, H.-C. Clemen, G. Dekoutsidis, A. Ehrlich, S. Grawe, V. Hahn, J. Hendricks, E. Järvinen, T. Klimach, K. Krüger, O. Krüger, J. Lucke, A.E. Luebke, A. Marsing, B. Mayer, J. Mayer, S. Mertes, M. Rubin-Zuzic, M. Moser, H. Müller, V. Nenakhov, M. Pöhlker, U. Pöschl, V. Pörtge, M. Rautenhaus, M. Righi, J. Röttenbacher, J. Schaefer, M. Schnaiter, J. Schneider, U. Schumann, N. Spelten, F. Stratmann, L. Tomsche, S. Wagner, Z. Wang, A. Weber, M. Wendisch, H. Wernli, B. Wetzel, M. Wirth, A. Zahn, H. Ziereis, M. Zöger (2025).  
  CIRRUS-HL: Picturing high- and mid-latitude summer cirrus and contrail cirrus above Europe with airborne measurements aboard the research aircraft HALO.  
  BAMS. doi:10.1175/BAMS-D-23-0270.1

- A. Ehrlich, S. Crewell, A. Herber, M. Klingebiel, C. Lüpkes, M. Mech, S. Becker, S. Borrmann, H. Bozem, M. Buschmann, H.-C. Clemen, E. De La Torre Castro, H. Dorff, R. Dupuy, O. Eppers, F. Ewald, G. George, A. Giez, S. Grawe, C. Gourbeyre, J. Hartmann, E. Jäkel, P. Joppe, O. Jourdan, Z. Jurányi, B. Kirbus, J. Lucke, A.E. Luebke, M. Maahn, N. Maherndl, C. Mallaun, J. Mayer, S. Mertes, G. Mioche, M. Moser, H. Müller, V. Pörtge, N. Risse, G. Roberts, S. Rosenburg, J. Röttenbacher, M. Schäfer, J. Schaefer, A. Schäfler, I. Schirmacher, J. Schneider, S. Schnitt, F. Stratmann, C. Tatzelt, C. Voigt, A. Walbröl, A. Weber, B. Wetzel, M. Wirth, M. Wendisch (2025).  
  A comprehensive in situ and remote sensing data set collected during the HALO–(AC)3 aircraft campaign.  
  Earth System Science Data. doi:10.5194/essd-17-1295-2025

- J. Mayer, B. Mayer, L. Bugliaro, R. Meerkötter, C. Voigt (2024).  
  How well can brightness temperature differences of spaceborne imagers help to detect cloud phase? A sensitivity analysis regarding cloud phase and related cloud properties.  
  Atmospheric Measurement Techniques. doi:10.5194/amt-17-5161-2024

- J. Mayer, L. Bugliaro, B. Mayer, D. Piontek, C. Voigt (2024).  
  Bayesian cloud-top phase determination for Meteosat Second Generation.  
  Atmospheric Measurement Techniques. doi:10.5194/amt-17-4015-2024

- M. Wendisch, S. Crewell, A. Ehrlich, A. Herber, B. Kirbus, C. Lüpkes, M. Mech, S.J. Abel, E.F. Akansu, F. Ament, C. Aubry, S. Becker, S. Borrmann, H. Bozem, M. Brückner, H.-C. Clemen, S. Dahlke, G. Dekoutsidis, J. Delanoë, E. De La Torre Castro, H. Dorff, R. Dupuy, O. Eppers, F. Ewald, G. George, I.V. Gorodetskaya, S. Grawe, S. Groß, J. Hartmann, S. Henning, L. Hirsch, E. Jäkel, P. Joppe, O. Jourdan, Z. Jurányi, M. Karalis, M. Kellermann, M. Klingebiel, M. Lonardi, J. Lucke, A.E. Luebke, M. Maahn, N. Maherndl, M. Maturilli, B. Mayer, J. Mayer, S. Mertes, J. Michaelis, M. Michalkov, G. Mioche, M. Moser, H. Müller, R. Neggers, D. Ori, D. Paul, F.M. Paulus, C. Pilz, F. Pithan, M. Pöhlker, V. Pörtge, M. Ringel, N. Risse, G.C. Roberts, S. Rosenburg, J. Röttenbacher, J.E. Rückert, M. Schäfer, J. Schaefer, V. Schemann, I. Schirmacher, J. Schmidt, S. Schmidt, J. Schneider, S. Schnitt, A. Schwarz, H. Siebert, H. Sodemann, T. Sperzel, G. Spreen, B. Stevens, F. Stratmann, G. Svensson, C. Tatzelt, T. Tuch, T. Vihma, C. Voigt, L. Volkmer, A. Walbröl, A. Weber, B. Wehner, B. Wetzel, M. Wirth, T. Zinner (2024).  
  Overview: Quasi-Lagrangian observations of Arctic air mass transformations -- Introduction and initial results of the HALO–(AC)$^{3}$ aircraft campaign.  
  Atmospheric Chemistry and Physics. doi:10.5194/acp-24-8865-2024

- A. Walbröl, J. Michaelis, S. Becker, H. Dorff, I. Gorodetskaya, B. Kirbus, M. Lauer, N. Maherndl, M. Maturilli, J. Mayer, H. Müller, R.A.J. Neggers, F.M. Paulus, J. Röttenbacher, J.E. Rückert, I. Schirmacher, N. Slättberg, A. Ehrlich, M. Wendisch, S. Crewell (2024).  
  Environmental conditions in the North Atlantic sector of the Arctic during the HALO–(AC)³ campaign.  
  Atmospheric Chemistry and Physics. doi:10.5194/acp-24-8007-2024

- J. Mayer, F. Ewald, L. Bugliaro, C. Voigt (2023).  
  Cloud Top Thermodynamic Phase from Synergistic Lidar-Radar Cloud Products from Polar Orbiting Satellites: Implications for Observations from Geostationary Satellites.  
  Remote Sensing. doi:10.3390/rs15071742

- T. Jurkat, J. Lucke, C. Schwarz, C. Deiler, F. Sachs, S. Kirschler, D. Menekay, C. Voigt, B. Bernstein, O. Jaron, F. Kalinka, A. Zollo, L. Lilie, J. Mayer, C. Page, B. Vié, A. Bourdon, R. Pereira Lima, L. Vieira (2023).  
  Overview of Cloud Microphysical Measurements during the SENS4ICE Airborne Test Campaigns: Contrasting Icing Frequencies from Climatological Data to First Results from Airborne Observations.  
  Conference Paper at SAE International. doi:10.4271/2023-01-1491

- J. Mayer, M. Obermüller, J. Denk, E. Frey (2021).  
  Snowdrift game induces pattern formation in systems of self-propelled particles.  
  Physical Reviews E. doi:10.1103/PhysRevE.104.044408





